#!/usr/bin/env node
// gen-catalog.mjs — the template catalog inside references/scene-spec.md, generated from every
// templates/scenes/<id>/schema.json and written between <!-- catalog:start --> and <!-- catalog:end -->.
//
//   node dev/gen-catalog.mjs           rewrite the catalog
//   node dev/gen-catalog.mjs --check   exit 1 when the catalog in the file is out of date

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const S = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TPL = join(S, "templates/scenes");
const DOC = join(S, "references/scene-spec.md");

/** "{title≤40, items[2..4]{icon, label≤22}}" — a one-line reading of a slot schema */
function slotLine(s, top = true) {
  if (!s) return "";
  if (s.type === "object" && s.properties) {
    const parts = Object.entries(s.properties).map(([k, v]) => `${k}${(s.required ?? []).includes(k) ? "" : "?"}${slotLine(v, false)}`);
    return top ? parts.join(", ") : `{${parts.join(", ")}}`;
  }
  if (s.type === "array") return `[${s.minItems ?? 0}..${s.maxItems ?? "n"}]${slotLine(s.items, false)}`;
  const t = Array.isArray(s.type) ? s.type.join("|") : s.type;
  if (s.maxLength) return `≤${s.maxLength}`;
  if (s.enum) return `(${s.enum.join("|")})`;
  if (t === "integer" || t === "number") return `:${t === "integer" ? "int" : "num"}${s.minimum != null ? ` ${s.minimum}–${s.maximum}` : ""}`;
  return t === "string" ? "" : `:${t}`;
}

const rows = readdirSync(TPL).filter((d) => existsSync(join(TPL, d, "schema.json"))).sort().map((id) => {
  const j = JSON.parse(readFileSync(join(TPL, id, "schema.json"), "utf8"));
  const variants = j.variants.map((v) => ((j.signatures ?? []).includes(v) ? `**${v}**` : v)).join(", ");
  const reveals = Object.entries(j.reveals ?? {}).map(([k, r]) => `${k}${r.range ? " (range)" : ""}${r.after ? ` >${r.after}` : ""}`).join(", ");
  const d = j.duration ? `${j.duration.min}–${j.duration.max} s` : "";
  return `| \`${id}\` | ${j.family} | ${variants} | ${slotLine(j.slots)} | ${reveals} | ${d} |`;
});
const lines = ["<!-- catalog:start -->",
  "Generated by `node dev/gen-catalog.mjs` from the schemas; **bold** = signature variant; preview: `templates/scenes/<id>/<variant>.jpg` (20 % | 85 %).",
  "", "| template | family | variants | slots (`?` optional, `≤n` characters, `[a..b]` items) | reveal keys | length |", "|---|---|---|---|---|---|",
  ...rows, "<!-- catalog:end -->"];

const doc = readFileSync(DOC, "utf8");
// write the catalog with the line endings the file already uses (CRLF on a Windows checkout)
const table = lines.join(/\r\n/.test(doc) ? "\r\n" : "\n");
const next = doc.replace(/<!-- catalog:start -->[\s\S]*?<!-- catalog:end -->/, () => table);
if (!doc.includes("<!-- catalog:start -->")) { console.error("✗ scene-spec.md has no <!-- catalog:start --> marker"); process.exit(1); }
if (process.argv.includes("--check")) {
  if (next.replace(/\r/g, "") !== doc.replace(/\r/g, "")) { console.error("✗ the catalog in references/scene-spec.md is out of date: run node dev/gen-catalog.mjs"); process.exit(1); }
  console.log(`catalog ok (${rows.length} templates)`);
} else {
  writeFileSync(DOC, next);
  console.log(`catalog: ${rows.length} templates written to references/scene-spec.md`);
}
